Follow tf structure to REP105 standard.
WHILL/ros_whill pull request #11
Opened 2019-04-25 04:53 UTC by aquahika

#8 
Delete base_footprint link.  Connect `odom` ->  `base_link` directly.

2019-04-25 04:54 UTC, aquahika commented
Should be merged after #10 has been merged.

2019-04-25 05:02 UTC, aquahika commented
Please review and approve it. @seiya0412  @horibirds

2019-04-26 04:27 UTC, seiya0412 commented on src/odom.cpp
> +const float base_link_height = 0.1325;
ここがハードコーディングされてる理由ってなんでしたっけ。base_link->odomのTFを吐くのがこのノードだから？

2019-04-26 04:27 UTC, seiya0412 commented on src/odom.cpp
> +const float base_link_height = 0.1325;
あと、マジックナンバーにするよりは何等かのパラメータから拾ってくるようにしたいです。

2019-04-26 04:43 UTC, aquahika commented on src/odom.cpp
> +const float base_link_height = 0.1325;
odom -> base_linkを直につなげたことにより、従来xacroで持っていたタイヤの半径分のオフセットがtf publisherのコードに出てきてしまいました。後ほど別Issue&pull-requestで対応しましょう。

2019-04-26 05:31 UTC, horibirds requested changes

2019-04-26 05:31 UTC, horibirds commented on launch/modelc.launch
> +    <param name="robot_description" command="$(find xacro)/xacro $(find ros_whill)/xacro/modelc.xacro"/>
@aquahika you can use $(arg model) here.

2019-04-26 06:24 UTC, aquahika commented on launch/modelc.launch
> +    <param name="robot_description" command="$(find xacro)/xacro $(find ros_whill)/xacro/modelc.xacro"/>
Fixed.

2019-04-26 07:09 UTC, horibirds approved these changes

2019-04-26 07:10 UTC, merged